const recipesData = [
  {
    id: 1,
    name: "Classic Margherita Pizza",
    cuisine: "Italian",
    image: "https://cdn.dummyjson.com/recipe-images/1.webp",
    rating: 4.6,
    reviewCount: 98,
  },
  {
    id: 2,
    name: "Vegetarian Stir-Fry",
    cuisine: "Asian",
    image: "https://cdn.dummyjson.com/recipe-images/2.webp",
    rating: 4.7,
    reviewCount: 26,
  },
  {
    id: 3,
    name: "Chocolate Chip Cookies",
    cuisine: "American",
    image: "https://cdn.dummyjson.com/recipe-images/3.webp",
    rating: 4.9,
    reviewCount: 13,
  },
  {
    id: 4,
    name: "Chicken Alfredo Pasta",
    cuisine: "Italian",
    image: "https://cdn.dummyjson.com/recipe-images/4.webp",
    rating: 4.9,
    reviewCount: 82,
  },
  {
    id: 5,
    name: "Mango Salsa Chicken",
    cuisine: "Mexican",
    image: "https://cdn.dummyjson.com/recipe-images/5.webp",
    rating: 4.9,
    reviewCount: 63,
  },
  {
    id: 6,
    name: "Quinoa Salad with Avocado",
    cuisine: "Mediterranean",
    image: "https://cdn.dummyjson.com/recipe-images/6.webp",
    rating: 4.4,
    reviewCount: 59,
  },
  {
    id: 7,
    name: "Tomato Basil Bruschetta",
    cuisine: "Italian",
    image: "https://cdn.dummyjson.com/recipe-images/7.webp",
    rating: 4.7,
    reviewCount: 95,
  },
  {
    id: 8,
    name: "Beef and Broccoli Stir-Fry",
    cuisine: "Asian",
    image: "https://cdn.dummyjson.com/recipe-images/8.webp",
    rating: 4.7,
    reviewCount: 58,
  },
  {
    id: 9,
    name: "Caprese Salad",
    cuisine: "Italian",
    image: "https://cdn.dummyjson.com/recipe-images/9.webp",
    rating: 4.6,
    reviewCount: 82,
  },
  {
    id: 10,
    name: "Shrimp Scampi Pasta",
    cuisine: "Italian",
    image: "https://cdn.dummyjson.com/recipe-images/10.webp",
    rating: 4.3,
    reviewCount: 5,
  },
];


export default recipesData;